services:
  user-service-db:
    image: postgres:17.2
    container_name: user-service-db
    restart: always
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    networks:
      - msproject-network
    volumes:
      - user-db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - msproject-network
    depends_on:
      - user-service-db
#      - user-service
#
#  user-service:
#    build: ./user-service
#    container_name: user-service
#    restart: always
#    depends_on:
#      - user-service-db
#    environment:
#      DB_HOST: user-service-db
#      DB_PORT: 5432
#      DB_NAME: user_db
#      DB_USER: user
#      DB_PASSWORD: password
#    ports:
#      - "8080:8080"
#    networks:
#      - msproject-network


networks:
  msproject-network:

volumes:
  user-db-data: