server:
  port: 8082

spring:
  application:
    name: emailTo-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:email_db}
    username: ${DB_USER:emailTo}
    password: ${DB_PASSWORD:emailTo}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    addresses: amqps://bxwltprb:UNjY4fGcbdba3zjEo7IdA4jxRMiRcaRQ@shrimp.rmq.cloudamqp.com/bxwltprb

broker:
  queue:
    email:
      name: default.email